### ISSUE TITLE
Timestamp column with default NULL

### ISSUE THREAD

**Issue by sanyatuning** [nwoltman/node-mysql-plus#3]
Hi 

I can't create timestamp columns with default null value.
`
const colName = db.ColTypes.timestamp().default(null);
`

I have a workaround, but this allways runs an alter table on sync
`
const colName = new ColumnDefinition('timestamp NULL').default(null)
`

Can you fix this for me?

This is the error what I got:
```
============= mysql-plus operations: ==============

type: ALTER_TABLE
SQL: ALTER TABLE `release`
       ADD COLUMN `approvedAt` timestamp DEFAULT NULL

===================================================


====== mysql-plus sync errored on operation: ======

type: ALTER_TABLE
SQL: ALTER TABLE `release`
       ADD COLUMN `approvedAt` timestamp DEFAULT NULL

===================================================

  alba:db sync Error: { Error: ER_INVALID_DEFAULT: Invalid default value for 'approvedAt'
    at Query.Sequence._packetToError (/home/sanya/Work/vcc-alba-irms/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/sanya/Work/vcc-alba-irms/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/sanya/Work/vcc-alba-irms/server/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/sanya/Work/vcc-alba-irms/server/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/home/sanya/Work/vcc-alba-irms/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/sanya/Work/vcc-alba-irms/server/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Socket.EventEmitter.emit (/home/sanya/Work/vcc-alba-irms/server/node_modules/sc-domain/index.js:12:31)
    at readableAddChunk (_stream_readable.js:176:18)
```

**Comment by nwoltman** [comment]
Fix released in v0.9.0

**Comment by sanyatuning** [comment]
Thanks!

**Comment by nwoltman** [comment]
No problem! Thanks for reporting the bug :)
